name: "Release"

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Typst
        uses: typst-community/setup-typst@v3
      - name: Generate assets
        run: mkdir -p output; for f in src/main.*.typ; do typst compile "$f" "output/curriculum-vitae.$(basename "$f" | cut -d. -f2).pdf" --font-path font --root .; done
      - name: Publish assets
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.pdf
          generate_release_notes: false
